### ISSUE TITLE
PHP Fatal error: Allowed memory size of 209715200 bytes exhausted...

### ISSUE THREAD

**Issue by jpscharf** [idleberg/Bootstrap-Listr#160]
When attempting to download a file, PHP tries to allocate enough memory to load the whole file.Can this be changed to either directly download or "chunk" the transfer?

**Comment by idleberg** [comment]
Can you please be more specific about how this happens? I'd like to be able to reproduce this.

**Comment by jpscharf** [comment]
Setup a site with download links to MS Office and Windows 7 on a DigitalOcean droplet with 512MB RAM:
* PHP 5.5.16
* NGINX 1.6.1

*Redacted Error*

2015/02/23 17:49:23 [error] 4950#0: *11219 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 209715200 bytes exhausted (tried to allocate 794841088 bytes) in /usr/share/nginx/share/www/dl/index.php on line 76" while reading response header from upstream, client: 0.0.0.0, server: share.example.com, request: "GET /dl/Microsoft/Microsoft%20Office%202013%20SP1%20x32.iso HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "share.example.com"

**Comment by idleberg** [comment]
I can't reproduce this, I could successfully load an Ubuntu image (~1.1GB) on using `memory_limit = 100M`. The only difference I noticed, is that the file is loaded in the browser rather than being offered as download, even though my MIME settings are alright.

Please do me the favour and replace your `index.php` with [this one](http://s.idleberg.com/index.php.zip). It uses the [readfile_chunked](http://stackoverflow.com/a/6914978/1329116) function rather than readfile.

**Comment by jpscharf** [comment]
That worked! Do you think it had something to do with me using nginx? Here is the relevant portion of my nginx config, I have the application running under a subirectory (i.e. https://example.com/dl ):

```
    location ~(^/dl/)(.*) {

        try_files $uri $uri/ /dl/index.php?path=$2;

        # Forward requests on to PHP-FPM
        location ~ \.php$ {
            include /etc/nginx/fastcgi_params;
            fastcgi_index index.php;
            fastcgi_intercept_errors on;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass unix:/var/run/php5-fpm.sock;
        }
    }
```

**Comment by idleberg** [comment]
I'm not familiar with nginx, but I'm thinking about how to best integrate the alternative readfile function. I don't see the harm in doing so, both versions behaved the same for me.
