### ISSUE TITLE
.txt files

### ISSUE THREAD

**Issue by tensei** [idleberg/Bootstrap-Listr#165]
would it be possible to display the content of a textfile in the body?

**Comment by idleberg** [comment]
Not sure what you mean. If you enable the viewer, you can display the content in a modal.

**Comment by tensei** [comment]
instead of table the content of txtfile

**Comment by idleberg** [comment]
I don't have plans for this, sorry

**Comment by tensei** [comment]
... ok thank you anyway

**Comment by idleberg** [comment]
I'll keep this issue open for now, since a future version might make it much easier to create custom views
