### ISSUE TITLE
ngnix

### ISSUE THREAD

**Issue by tensei** [idleberg/Bootstrap-Listr#171]
how do i use this with ngnix?
the .htacces
htacces to ngnix converter gives me this

# nginx configuration
location / {
    if (!-e $request_filename){
        rewrite ^(.+)$ /index.php?path=$1 break;
    }
}
but it doesnt work

**Comment by mathieu-aubin** [comment]
In case you are still wondering (and if that was even the question - wich i am pretty sure of): Working location settings for nginx are as follows - you must still include your php-fpm params as per usual to get nginx to proxy php correctly...

location / {
if (!-e $request_filename) {
rewrite ^(.+)$ /index.php?path=$1 break;
}
# Your normal / location settings here (php_params etc)
}

**Comment by mathieu-aubin** [comment]
After a bit of trying - it does work... but only barely! just displays the index nicely, as for all the other functionallities... it's a big no-no. I should try and wrap my head around this - not so much cuz i need the thing but mostly for fun and to profit others!
If you have a working nginx conf let me know thx

**Comment by idleberg** [comment]
I never used nginx myself, so I don't have any experience. I appreciate your effort. Let me know when you find a way to fully support this and I'll include it.
