### ISSUE TITLE
Time Ago vs Time Stamp

### ISSUE THREAD

**Issue by dinosaw** [idleberg/Bootstrap-Listr#225]
Is there a way you could implement a toggle in the config file to change the "Modified" column to show the actual date / time it was modified, as opposed to the "time ago"? And if not, would you be able to tell me how I could manually do it myself? Thanks for this!

**Comment by idleberg** [comment]
Quick solution: change `time_ago($item['mtime'])` on [line 497](https://github.com/idleberg/Bootstrap-Listr/blob/master/src/index.php#L497) to `$item['iso_mtime']`.

Long term solution: I will put it on my list

PS: did you see the tooltip when you hover over the time?
