### ISSUE TITLE
Looks for files in /dist/ folder and not in /_public/

### ISSUE THREAD

**Issue by nnoided** [idleberg/Bootstrap-Listr#227]
I have files in /_public/, they show up in the directory but I get a 404 on them. If I put them in /dist/ as well, it'll work. Is this a bug?

Nginx + debian

**Comment by idleberg** [comment]
Did you have a look at the [FAQ](https://github.com/idleberg/Bootstrap-Listr/wiki/FAQ)? I'm not familiar with nginx, but I know people have successfully used Bootstrap Listr with nginx.
