### ISSUE TITLE
Gulp error in the command line

### ISSUE THREAD

**Issue by GuiAlmeida** [idleberg/Bootstrap-Listr#228]
I am using the Bootstrap-List to style directory search, but when I use "gulp" comes this error using the same I as an administrator prompt

[22:06:04] Using gulpfile C:\Git\Bootstrap-Listr\gulpfile.js
[22:06:04] Starting 'build_hjs'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn npm ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by idleberg** [comment]
Unfortunately, I cannot test this on Windows. What helps sometimes is running `gulp clean` first, though an empty `dist/` foldder doesn't seem to be the problem here.

**Comment by GuiAlmeida** [comment]
but what is the correct location which is in my files dist/ or _public /?

**Comment by idleberg** [comment]
(Rename and) deploy the `dist` folder to your server. You might have to adjust the `RewriteBase` setting in `.htaccess`. All files you want visible on your webserver go into `_public`. Point your browser to the address of the `dist` folder.

**Comment by GuiAlmeida** [comment]
did gulp eating clean it turned out the dist folder, I create a again?

**Comment by idleberg** [comment]
yes

**Comment by GuiAlmeida** [comment]
but what is the correct procedure? I enter the dist folder and use the "gulp" or use my own gulp and point to the dist folder?, excuse my doubts because I liked your prjeto and wanted to be able to use it in windows

**Comment by idleberg** [comment]
``` bash
git clone https://github.com/idleberg/Bootstrap-Listr
cd Bootstrap-Listr
npm install
# gulp clean (to delete previous setup)
gulp
```

Deploy `dist`

**Comment by idleberg** [comment]
Anyway, since your initial issue seems to
