### ISSUE TITLE
nl_NL translation

### ISSUE THREAD

**Issue by thorade** [idleberg/Bootstrap-Listr#233]
I believe the files 
https://github.com/idleberg/Bootstrap-Listr/blob/master/dist/l10n/nl_NL/LC_MESSAGES/messages.mo 
https://github.com/idleberg/Bootstrap-Listr/blob/master/src/l10n/nl_NL/LC_MESSAGES/messages.mo 
should be binary!?

**Comment by idleberg** [comment]
I'm currently travelling without access to a computer. On my phone the files look like the source code of the GitHub page. I'd assume they look differently when you clone the repository. The translation files tested before I added them to the repo.

**Comment by thorade** [comment]
Thanks for answering, there is no need to hurry. I am not even sure if anything is broken, I was just wondering, because the mo files for the other languages are binary:
de_DE
https://github.com/idleberg/Bootstrap-Listr/blob/master/dist/l10n/de_DE/LC_MESSAGES/messages.mo
https://github.com/idleberg/Bootstrap-Listr/blob/master/src/l10n/de_DE/LC_MESSAGES/messages.mo
versus nl_NL
https://github.com/idleberg/Bootstrap-Listr/blob/master/dist/l10n/nl_NL/LC_MESSAGES/messages.mo
https://github.com/idleberg/Bootstrap-Listr/blob/master/src/l10n/nl_NL/LC_MESSAGES/messages.mo

**Comment by idleberg** [comment]
Actually, you were right. Fixed in #234, thanks!

**Comment by thorade** [comment]
Thanks for the quick fix!
