### ISSUE TITLE
Disallow download certain file types

### ISSUE THREAD

**Issue by systems-rebooter** [idleberg/Bootstrap-Listr#242]
Hey there!

Thanks for the awesome job you guys done! 

I am interested in disallowing certain file types download. But still showing up those files via Listr. Viewer can pop up while clicked on such files, but with configurable information, why this type of file disallowed from previewing / downloading. 

For now, I will be fine with graying out all of the files temporary, but still allow directory browsing. It would be awesome if you can give me quick advice on what part of code i should comment out to achieve that  Thanks you so much!

**Comment by idleberg** [comment]
I don't know if that's even possible. My first thought was that this is something you would do using file-permissions, but I haven't managed to achieve that. Maybe the [File-directive](https://httpd.apache.org/docs/current/mod/core.html#files) allows you to do that.

Any other way I can think of would require a major rewrite and comes with several downsides (e.g. breaking direct links).

**Comment by systems-rebooter** [comment]
Yeah, one of the mine ideas was to achieve this on nginx side as well, but it seems a bit dull for me.

 The other option I am thinking about is if there is no way to gray out all files (yeah, that sounds not so robust, but i really need this) maybe i can just call empty modal with _'Sorry this file is not available now for previewing'_ text And for direct file calling (via browser bar, for instance) give back 403.. If 403 will appear in modal just fine - i will customize error page and be happy with it. 

Thanks!

**Comment by idleberg** [comment]
At some point (think `3.0.0` or so), I want to extend the idea of supporting virtual file systems. That would, for instance, allow you to supply a JSON with file-names and the URL of their actual location. Or in case of the existing virtual files, include embed codes. That system will make it far easier to handle permissions for single files and folders.

**Comment by systems-rebooter** [comment]
Yep, i totally understand. If something needs to be done, its better do it the right way! 
And yeah,  virtual files, rocks! I was soooo impressed how you implemented this!
