### ISSUE TITLE
Set cutom_title to basename

### ISSUE THREAD

**Issue by systems-rebooter** [idleberg/Bootstrap-Listr#243]
Hey,

When specifying a page title, overriding the default _Index of (URL)_ can it possible to set it to 

`basename` _keyword_

I mean the following

```
Index of example.com/A/B/C --> C keyword
Index of example.com/1/2/3 --> 3 keyword
```

Thanks!

**Comment by idleberg** [comment]
That's a good idea, will put it on my todo list!

**Comment by systems-rebooter** [comment]
Cool. Thanks @idleberg

**Comment by systems-rebooter** [comment]
Quick question, may I trim _Index of_ and leave only URL in `cutom_title`?

**Comment by systems-rebooter** [comment]
Just noticed one small bug - if folder contains non-ascii chars, google mess it up converting to HTML %-likes in search results. 

<img width="1250" alt="screen shot 2015-11-03 at 12 26 35" src="https://cloud.githubusercontent.com/assets/8888190/10906131/af635a0c-8227-11e5-9dc6-5f04d14e21a3.png">

So this enhancement will be really cool!

**Comment by idleberg** [comment]
The bug should've be fixed in 5e0d750f1a57347a954e98cf1b7c50e5fba75ac3

**Comment by idleberg** [comment]
I probably misunderstood your request for displaying the basename in `<title>` at first. On second thought I agree that this should be the default. Added in 4721551731cf6eb5987016076403cd742f5e22d9.

**Comment by systems-rebooter** [comment]
Hey @idleberg 

Thanks for the hot fixes. Yeah, its working as expected. Replacing 

```
 $index = "Index of $folder";
```
with 
```
$index = "$folder keyword";
```

in `listr-functions.php` is setting title to exactly how I needed. 

Closing the issue.
