### ISSUE TITLE
Wildcard for Ignored / Hidden files 

### ISSUE THREAD

**Issue by systems-rebooter** [idleberg/Bootstrap-Listr#244]
Hey!

Is it possible to use wildcard for ignored / hidden files? I've tried but had no luck.

Thanks

**Comment by idleberg** [comment]
That's already on the list :smile:

**Comment by systems-rebooter** [comment]
Huh, i see :) Will it be crazy idea to json few thousand files? =)

```
$ time find . -mindepth 4 -maxdepth 4 -type f -name \*jpg | wc -l
33744

real	16m51.506s
```

**Comment by systems-rebooter** [comment]
@idleberg, my dear friend

Did you have a chance to look trough this issue? ;-]

**Comment by idleberg** [comment]
There *should* be a new release during the holidays

**Comment by systems-rebooter** [comment]
Cool. Thanks!

**Comment by systems-rebooter** [comment]
@idleberg I've tested your `2.3.0-alpha` and wildcard filter working like a charm! Thanks for implementing this! 

Small improvement to this feature would be a reverse wildcard for ignoring/hiding files if you have a big array of them (i.e. `ignore/hide all files, but *.txt` and `*.css`). But if you don't implement it, I'll understand since main requested feature working superbly! Thanks again!
