### ISSUE TITLE
Problem with locate

### ISSUE THREAD

**Issue by eesnaola** [idleberg/Bootstrap-Listr#250]
In the last version not work the parameter locate. Thanks
Sorry for my bad English.

**Comment by idleberg** [comment]
I'm afraid I don't understand, what's the parameter locate?

**Comment by eesnaola** [comment]
I try changing the language and did not work, i change from file config to es_ES but dont work.

**Comment by idleberg** [comment]
Hmm, it works for me. I don't think there have been made any changes to the translations, but just in case, overwrite the `l10n` folder.
