### ISSUE TITLE
[Suggestion] Remove file

### ISSUE THREAD

**Issue by Marox44** [idleberg/Bootstrap-Listr#251]
Hi! 

I've just thought that it would be convenient to have a delete file option.
It might have just been an additional **optional column** with a simple trash-can-like icon :wink: 

As for future enhancements, how about an option to select & delete multiple files at once?  

Great piece of code btw :wink: lightweight, yet really useful and all-purpose.

Thanks and keep it up!

**Comment by idleberg** [comment]
In my opinion, that would require a solid user rights management (and then a database). Maybe at some point in the future, there will be a plugin system. Let's see, for now this is a viewer, not a management tool!
