### ISSUE TITLE
Folders with lots of objects loading significant time 

### ISSUE THREAD

**Issue by systems-rebooter** [idleberg/Bootstrap-Listr#257]
Hi,

When a folder contains lots of objects it takes significant time to load. I've tested with few thousands elements and it loads almost forever. Would it be possible to speed things up somehow or maybe load the big amount of elements in batches? 

Thanks!

**Comment by idleberg** [comment]
I have no problems loading a folder containing 5,000 files

**Comment by systems-rebooter** [comment]
Hi @idleberg 

Below are the timelines I'm getting:

```
$ time find . -mindepth 1 -maxdepth 1 -type d  -print0 | while read -d '' -r dir; do     files=("$dir"/*);     printf "%5d folders in directory %s\n" "${#files[@]}" "$dir"; done | sort -nr

 8297 folders in directory ./D
 7293 folders in directory ./S
 6641 folders in directory ./M
 5189 folders in directory ./A
 3816 folders in directory ./T
 3680 folders in directory ./C
 3660 folders in directory ./B
 3652 folders in directory ./P
 3523 folders in directory ./R
 3412 folders in directory ./J
 2671 folders in directory ./F
 2619 folders in directory ./L
 2485 folders in directory ./K
 2285 folders in directory ./E
 2273 folders in directory ./G
 2217 folders in directory ./N
 1901 folders in directory ./H
 1333 folders in directory ./I
 1243 folders in directory ./O
 1223 folders in directory ./V
 1101 folders in directory ./W
  624 folders in directory ./U
  476 folders in directory ./Y
  465 folders in directory ./Z
  307 folders in directory ./X
  207 folders in directory ./Q

real	0m0.202s
user	0m0.201s
sys	0m0.002s
```

Directory `D` (contains `8297` folders, load time: `18.76s` of total page load `21.76s`)

<img width="869" alt="screen shot 2015-12-15 at 10 41 41" src="https://cloud.githubusercontent.com/assets/8888190/11806078/4648ed12-a319-11e5-851d-16a6d9745525.png">

Directory `S` (contains `7293` folders, load time: `19.55s` of total page load `20.43s`)

<img width="869" alt="screen shot 2015-12-15 at 10 44 13" src="https://cloud.githubusercontent.com/assets/8888190/11806085/52afde94-a319-11e5-8c16-6924d09a58f0.png">
