### ISSUE TITLE
Breadcrumbs links loop if path contains special chars like ():& 

### ISSUE THREAD

**Issue by systems-rebooter** [idleberg/Bootstrap-Listr#267]
Hello,

Breadcrumbs links seem to be looping if path contains special chars like ():& (and maybe some others)

Steps to reproduce:

1) Create paths like `/1/:2/` `/1/(2)/`.
2) Directly access via web browser URI`s: 

http://bootstrap-listr.com/1/:2/
http://bootstrap-listr.com/1/(2)/

2) Click on any breadcrumbs path links, but `home`. This should loop over and append link to trailing slash, so we get 404 URL`s:

http://bootstrap-listr.com/1/:2/1/
http://bootstrap-listr.com/1/(2)/1/

or 

http://bootstrap-listr.com/1/:2/:2/
http://bootstrap-listr.com/1/(2)/(2)/

I'm suspecting URL encoding/decoding issue. If we try to replace special chars with `( - %28` `) - %29` `: - %3A`, everything working nicely. Also, there are no issues with UTF chars like `Ł  Ö 정  ᴷ   ど  〆  み 無  藤`.

Thanks!

**Comment by idleberg** [comment]
Use the stable version
