### ISSUE TITLE
Add screenshot instead of a demo only

### ISSUE THREAD

**Issue by tristanbes** [idleberg/Bootstrap-Listr#288]
Hi,

The demo is crashed 
`Fatal error: Call to undefined function is_error() in /kunden/whyeye.org/webseiten/idleberg.com/demo/Bootstrap-Listr-2/listr-template.php on line 8`

You should add screenshot instead of relying on demo only that can crash.

**Comment by mathieu-aubin** [comment]
@tristanbes -- i understand your point and it is a valued one. The thing with Bootstrap-Listr is that a screenshot wouldn't do justice to the functionnalities of the 'app'. It's unfortunate that you got problem with the demo. Hopefully you got everything sorted.

After 22 days of writing this issue report;
**DID YOU get the demo to work? If so, please reply here and close your issue.**

@Idleberg: never had a problem with the demo myself but just in case, maybe you should add (for the demo only) this code in the index.php file

`ini_set('display_errors', '0');`

**Comment by idleberg** [comment]
I was thinking about hosting a static HTML version on GitHub pages, because I agree, that screenshots don't do much justice.
