### ISSUE TITLE
Bootstrap 2.24 PLEASE HELP.

### ISSUE THREAD

**Issue by smartpapers** [idleberg/Bootstrap-Listr#299]
Hello @idleberg.
Can you please tell me how can I change the background color of this plugin?
Can I change icons? If so how to change .pdf icon?
How can I edit the footer so I can add my website's "Back to Home" link? 
And can i display a "parent directory button" inside sub folders?

Please help me anyone!!!

Thanks in advance.

**Comment by idleberg** [comment]
> Can you please tell me how can I change the background color of this plugin?

This is not a plugin.

You can build your own custom Bootstrap 4 theme. For basic changes, it's probably enough to change [`_variables.scss`](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss) and then recompile it.  Alternatively, you can overwrite the Bootstrap styles in a custom style-sheet and [append](https://github.com/idleberg/Bootstrap-Listr/wiki/Understanding-config.json#assets) it.

> Can I change icons? If so how to change .pdf icon?

If the [default themes](https://github.com/idleberg/Bootstrap-Listr/tree/master/src/themes) don't suit you, you can create your own. The format is pretty self-explanatory, you need to assign the icon's class-name to a file-extension. If your theme requires a different icon font, you need to [append](https://github.com/idleberg/Bootstrap-Listr/wiki/Understanding-config.json#assets) it's style-sheet.

> How can I edit the footer so I can add my website's "Back to Home" link?

You can't without editing the PHP template.

**Comment by smartpapers** [comment]
Thank you so much for replying @idleberg :)
Yes I figured out almost everything just 2 more questions.

1) Can I make a parent directory link at the top of table (if access to parent directory exists)

2) I just want to change the background of the table to "Grey" If there is anything I can append from the provided source code by you please specify the file. Or shall I make a new bootstrap theme?

**Comment by idleberg** [comment]
> 1) Can I make a parent directory link at the top of table (if access to parent directory exists)

Again, you'd have to edit the code

> 2) I just want to change the background of the table to "Grey" If there is anything I can append from the provided source code by you please specify the file. Or shall I make a new bootstrap theme? 

That's your decision. Personally, I probably would want to avoid another HTTP request for a style-sheet, so I'd customize the theme (e.g. in the [Bootstrap customizer](https://getbootstrap.com/customize/#tables))

Otherwise, append your style-sheet:

```css
.table {
    background: grey;
}
```

3) How can I edit the php (Which tag) to put a Header title on top of page. I can't find <head> or <body> tag in the php's.

Use search to find [`<head>`](https://github.com/idleberg/Bootstrap-Listr/search?utf8=%E2%9C%93&q=%3Chead%3E) and [`<body>`](https://github.com/idleberg/Bootstrap-Listr/search?utf8=%E2%9C%93&q=%3Cbody%3E) and

**Comment by smartpapers** [comment]
@idleberg  Thank you. Everything is working perfect now.

Can i change the title of tab i.e " Index of FOLDER " to  " FOLDER | Website Name "?

**Comment by idleberg** [comment]
> Can i change the title of tab i.e " Index of FOLDER " to " FOLDER | Website Name "?

No, but you can set `custom_title` in `config.json`

> And can i rearrage the position of "Search" bar? to left?

You would have to remove the offset-classes in the markup

**Comment by mathieu-aubin** [comment]
Idleberg, i admire your patience! You are one of a kind!

**Comment by mathieu-aubin** [comment]
smartpapers  -- whenever i need to modify anything from the already amazing Bootstrap-Listr, i modify listr-template.php which is (correct me if i'm wrong) the file being processed to display html content.

If you wanted to add a header (if i understand correctly) under the navigation bar, you would simply have to edit listr-template.php and add your custom html code. Don't forget, this uses bootstrap (aka twitter bootstrap) so your changes should take adavatages of bootstrap's grid system.

Did you achieve to get everything you wanted to work? If not, it would be my pleasure to lighten idleberg's load and assit you in such. Please reply here so everyone is notified and e-mail me at mathieu@zeroserieux.com. I will reply publicly here and privately in email. Consider supporting the project with a donation, i'm sure they appreciate the gesture!

**Comment by smartpapers** [comment]
Hey there,
Yes I did all of it. Thank you for your help guys. :)

If there is any possibility that I can show a notification on top below the
header.

**Comment by idleberg** [comment]
> If there is any possibility that I can show a notification on top below the
> header.

It's on the list, but probably not before `3.0.0` comes out

**Comment by mathieu-aubin** [comment]
@smartpapers 
Hi, can you be more precise? Do you want to notification to be under the navigation bar? over/under the breadcrums? can you supply a picture of where you would want your 'notification'?
