### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by fcpauldiaz** [idleberg/Bootstrap-Listr#302]
How do I use this ? I can't find instructions.

**Comment by idleberg** [comment]
1. Clone the repository
2. [Build](https://github.com/idleberg/Bootstrap-Listr#building)
3. [Configure](https://github.com/idleberg/Bootstrap-Listr/wiki/Understanding-config.json) your setup (optional)

Most common

**Comment by fcpauldiaz** [comment]
So gulp will build some assets and how do I use the assets? Is it just adding class="something" ?

**Comment by idleberg** [comment]
You just upload the entire `build` folder. The build tools are meant to streamline the assets according to your needs, to avoid unnecessary overhead.

**Comment by fcpauldiaz** [comment]
So I config the build folder with the config.json inside it? I see that the demo version attaches directly the assets, that's the way to do it ?

**Comment by idleberg** [comment]
The build task makes some changes to `config.json`, but you can override these at any time. You deploy the entire build-folder and place your files inside `__public`.

Note: If you're using the latest stable version, the equivalent of the build-folder is the dist-folder. Also, there's a ready-to-use folder included in the download.

**Comment by fcpauldiaz** [comment]
Thanks!
