### ISSUE TITLE
A little help with "Preview" of PDFs.

### ISSUE THREAD

**Issue by smartpapers** [idleberg/Bootstrap-Listr#309]
@idleberg 

Hey there, I was wondering if there is any method through which I can stop the "Preview" of .pdf or any file.

Whenever I Click on the files it shows a pop-up box showing a small preview of the file and gives options of "Close" or "Open" 
I want it to be directly opened in a newtab. i.e:

When i click on the file "SomeDocument.pdf" it opens in a new window/tab.

Can you please help me with this?
Thanks.

**Comment by idleberg** [comment]
In [`config.json`](https://github.com/idleberg/Bootstrap-Listr/wiki/Understanding-config.json), you can disable the viewer altogether (see `enable_viewer') or define for which file extensions it works (see `viewer`).
