### ISSUE TITLE
Run on Nginx

### ISSUE THREAD

**Issue by soulruins** [idleberg/Bootstrap-Listr#311]
Hello. How run this script on Nginx?

**Comment by idleberg** [comment]
I don't have the slightest idea

**Comment by idleberg** [comment]
Does [this config](https://github.com/idleberg/Bootstrap-Listr/wiki/FAQ#why-am-i-getting-404-errors-on-subfolders-with-nginx) not work? (cc @mathieu-aubin)

**Comment by soulruins** [comment]
Oh! Thanks! It's work config. My rewrite rule was not correct.
