### ISSUE TITLE
Issue With max_execution_time

### ISSUE THREAD

**Issue by crunchprank** [idleberg/Bootstrap-Listr#316]
There may be no way around this, and I'm not familiar enough with PHP applications to suggest anything different, but I'm running into an issue where if a download takes more than X seconds, the download is canceled on the user's end. This causes a problem when trying to serve large files, or when someone on a slower internet connection is attempting to download.

The reason for this looks to be due to my server's max_execution_time setting. I have it set to the default PHP configuration of 30 seconds. This has in the past served me well and I haven't ran into any issues with other PHP applications. But basically if someone is downloading a file and it takes longer than 30 seconds, this is produced in the Apache logs:

```
[Sat Apr 16 12:22:45.663949 2016] [:error] [pid 1957] [client x.x.x.x:x] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/listr-functions.php on line 296...
```

The line 296 seems to refer to a bit of code dealing with the ``readfile_chunked`` snippet. Which I do have ``read_chunks`` set to true in the config.json. It was the only way I could serve large files.

I could increase my server's PHP execution time, but I'm thinking there must be some other way around this considering the variables that come into play such as the file size and user's connection which you never know how long a download is going to take.

Let me know if I can provide any other information.

**Comment by idleberg** [comment]
The only way around this *might* be a separate `download.php` that sends the original file to the user. Maybe `v3.0.0` will fix this without any extra work, since file management is handled by a third-party module. Otherwise, I don't think I have time and resources to look into this before the first alpha of `v.3.0.0` drops.

**Comment by crunchprank** [comment]
Alright, no worries! It only poses a problem with a few of the larger files I have. Other than that the app works great. Thanks!
