### ISSUE TITLE
Bootstrap's JS is included twice

### ISSUE THREAD

**Issue by wolfy1339** [idleberg/Bootstrap-Listr#320]
In the latest master version, I have seen that Bootstrap's JS gets included twice.
That causes the JS to conflict with each other and makes the drop-downs stop working.
It it included here: https://github.com/idleberg/Bootstrap-Listr/blob/master/src/listr-functions.php#L135-138
and here: https://github.com/idleberg/Bootstrap-Listr/blob/master/src/listr-functions.php#L149-L157

**Comment by wolfy1339** [comment]
@idleberg The commit that introduced this is dfa18e375351d090a384bc94e3e39db671236aff

**Comment by idleberg** [comment]
Thanks, I already fixed that but never committed the change. Will do now!

**Comment by wolfy1339** [comment]
Fixed by the merge of 2.3-dev into master
