### ISSUE TITLE
Add a feature to download files

### ISSUE THREAD

**Issue by KariyakiLP** [idleberg/Bootstrap-Listr#321]
Add a feature in the viewer to Download the files or when viewer disabled a direct download feature...

**Comment by idleberg** [comment]
If you want to overwrite the default behaviour how certain files are treated, displayed in the browser or downloaded, you need to tweak your Apache settings accordingly.

**Example**:

    <FilesMatch "\.(?i:gif|jpg|png|txt)$">
      Header set Content-Disposition attachment
    </FilesMatch>

The setting above will download the given file-types, rather than displaying them in your browser.

**Comment by KariyakiLP** [comment]
Ok that not that what i want

Better Option is a download Button in the Viewer

**Comment by idleberg** [comment]
The “Open” button in the viewer is equivalent to the file links when the viewer is disabled. In `v2.3.0` is has already been re-labeled “Download”, because it seemed to have confused people.
