### ISSUE TITLE
Change the function of "Open" button.

### ISSUE THREAD

**Issue by smartpapers** [idleberg/Bootstrap-Listr#343]
Hi there @idleberg @camilstaps @mohdaminyuddin @sboulema 

I don't know if its possible or not but It will be really helpful to me if you guys can tell me just one thing.
I have 2 concerns solving either one of them will work for me.

1) Can I somehow make this plugin open files in a new tab or window. There won't be any folders in my listings just pdf or doc files will be there. I want that if a person clicks on any file that file should open in a new tab. (I have disabled the viewer already) and I want it to be the default function of click/tap. Right clicking and forcefully opening it in a new tab is not what I want. 

2) When the file viewer opens. It shows 2 buttons at the end. "Open" "Close" can I somehow change the code or modify the code for the "Open" button so that when the person clicks or taps open that file should open in a new tab or window. Maybe I can add something like "target=_blank" or anything.

I really need this work and by far your plugin was the best directory lister I found on the internet.
Please help me. I would be very thankful to all of you.

Thanks.

**Comment by camilstaps** [comment]
There is no need to tag people. When you open an issue, the people that have the repository on their watchlist will get a notification any way.

**Comment by idleberg** [comment]
If you need that feature, you will have to edit the source

* in the [viewer](https://github.com/idleberg/Bootstrap-Listr/blob/2.3-dev/src/listr-template.php#L51) (add `target="_blank"`)
* in the [main file](https://github.com/idleberg/Bootstrap-Listr/blob/2.3-dev/src/index.php#L687) (add `target=\"_blank\"`)

**Comment by smartpapers** [comment]
$table_body .= "<a ". implode(" ", $modal_attr)." href=\"" . htmlentities(rawurlencode($item['bname']), ENT_QUOTES, 'utf-8' **target=\"_blank\"**)

<a href="#" **target="_blank"** class="btn <?php echo $btn_primary ?> fullview" download><?php echo _('Download')?></a>

Do you mean like this?

**Comment by idleberg** [comment]
How did you get *that* job without basic knowledge of HTML or PHP?

Just put it as the first attribute inside the `a` tag , e.g. ` $table_body .= "<a target=target=\"_blank\"".`
