### ISSUE TITLE
Removing a column! 2.3.0 Alpha-4

### ISSUE THREAD

**Issue by smartpapers** [idleberg/Bootstrap-Listr#346]
Greetings! @idleberg 

I am using your plugin bootstrap listr v2.3 alpha1.
I wanted to know if I can remove a column from the Listr.
I don't want the Sr no (#) Column. Can I remove it?

Your help will be really appreciated. 
Thanks!

**Comment by idleberg** [comment]
No you can't

**Comment by smartpapers** [comment]
Can I hide it in mobile devices? Like nothing can be done about it?

**Comment by smartpapers** [comment]
And apart from that I liked the small font of 2.3 version. In Alpha4 it is really big and causes trouble in mobile devices because my file names are long. Is there a way I can bring the search bar in the middle of the screen like in alpha4 version on mobile devices?

**Comment by smartpapers** [comment]
@idleberg 
Oh and btw I figured it out. 
in the config.json there is an option to hide the "count" column. 
I think you should learn more about your plugin.

Thanks.

**Comment by idleberg** [comment]
And I think you should STFU

**Comment by idleberg** [comment]
[See the FAQ](https://github.com/idleberg/Bootstrap-Listr/wiki/FAQ#how-can-i-hide-the-counter-in-bootstrap-v23)
