### ISSUE TITLE
Search Form don't work

### ISSUE THREAD

**Issue by geraldvergne2016** [idleberg/Bootstrap-Listr#350]
Hi,

Boostrap-Listr is a very good script.

I have a small problem the search form don't work.

Could you help me ?

Best regards.

**Comment by idleberg** [comment]
Did you include all JS assets? Is there an error in your browser's console?

**Comment by tstrotz** [comment]
I'm also having the same issue. It looks like there are assets missing from the download. See attached from Chrome console. Any ideas? Trying to get it working on IIS on Windows Server. So far all looks good except for the search. This thing is awesome, definitely want to get it working - thanks!
![capture](https://cloud.githubusercontent.com/assets/24739901/21463691/ad0f6c72-c921-11e6-94db-637ce979bb4a.PNG)

**Comment by geraldvergne2016** [comment]
Hi,

In Google Chrome some files can't be loaded.

![01](https://cloud.githubusercontent.com/assets/24703574/21465610/10ad888e-c9ab-11e6-9f7d-9e9f35d78cd7.jpg)

I can't find it on Github.

Could you help me ?

Bests regards.

**Comment by idleberg** [comment]
You will have to run the build task (see README)

**Comment by geraldvergne2016** [comment]
Hi,

I read the file and I build a new script.

I had many errors.

Bests regards.

**Comment by idleberg** [comment]
Could it be caused by the extra `/`in you URL?

**Comment by tstrotz** [comment]
Attached is an error log from running the build on my server. Any ideas? Thanks!
[npm-debug.txt](https://github.com/idleberg/Bootstrap-Listr/files/675959/npm-debug.txt)

**Comment by idleberg** [comment]
@tstrotz You need to run Node 6 (or higher)

**Comment by idleberg** [comment]
@geraldvergne2016 @tstrotz It would really help if you both used the [issue template](https://github.com/idleberg/Bootstrap-Listr/blob/master/.github/ISSUE_TEMPLATE.md)
