### ISSUE TITLE
Integrate Bootstrap Listr Alpha in Wordpress

### ISSUE THREAD

**Issue by husnaintariq01** [idleberg/Bootstrap-Listr#360]
Hello developers,

I wanted to ask can I add bootstrap listr to my wordpress website? Like in a page? 

What I want is that I have this layout of a theme, like a regular blog with sidebars and menus etc.
I want this listr to be visible in the post area. I can achieve such a thing with iframe inside the post area but that makes the page too slow. Any other method to integrate this in a wordpress page/post will be very helpful...

Thanks a lot.

**Comment by idleberg** [comment]
This is not an issue.

Anyway, you would probably have to create your own WordPress plugin for this. For details refer to the WordPress Codex.
