### ISSUE TITLE
Wrong detection of root dir with subdomain

### ISSUE THREAD

**Issue by beruic** [idleberg/Bootstrap-Listr#362]
## Prerequisites

* [x] Are you running the latest version of Bootstrap Listr (**stable** or alpha/beta)?
* [x] Did you check your browser's console for errors? See how in [Chrome](https://developers.google.com/web/tools/chrome-devtools/console/#open_as_panel), [Firefox](https://developer.mozilla.org/en/docs/Tools/Browser_Console), [Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/f12-devtools-guide/console/))
* [ ] Did you build a distribution? Use `npm run build`
* [ ] Are you running the Node v6 (or higher)?
* [x] Did you check the [FAQ](https://github.com/idleberg/Bootstrap-Listr/wiki/FAQ)?
* [x] Did you [perform a cursory search](https://github.com/idleberg/Bootstrap-Listr/issues) to see if your issue has already been reported?

## Description

I host my stuff at http://one.com. They have a feature where each folder in your root directory becomes a subdomain, so my file listing is available at both http://download.kragenet.dk/billeder and http://kragenet.dk/download/billeder, but I would like to only use the first one. When you visit the root (http://download.kragenet.dk/billeder/) everything is ok, but entering the subdir http://download.kragenet.dk/billeder/Gulvvarme/, the home url is wrongly detected to http://download.kragenet.dk/download/billeder, which makes CSS and JS for modals fail loading.

This could probably be fixed by just adding a config for overriding normal root url detection, but it would be cool if it just worked automatically.

PHP info: http://info.kragenet.dk/

**Comment by idleberg** [comment]
Could this be a case of server configuration as mentioned in the [FAQ](https://github.com/idleberg/Bootstrap-Listr/wiki/FAQ#why-am-i-getting-a-404-error-when-clicking-a-link)?

**Comment by beruic** [comment]
It might. I think I might have overlooked something ehre. Thanks! I will test immediately.

**Comment by beruic** [comment]
It seems the issue was that the root dir change whether I was at the root page or at a sub dir.

You may have an error in your FAQ. you write that:
> If you run Bootstrap Listr in /html/files, this should be `RewriteBase files/`.

i my case I had to write `RewriteBase /billeder`, but I am far from being an expert in `.htaccess`.

**Comment by beruic** [comment]
This however also makes http://kragenet.dk/download/billeder useless, but I can live with that.
